### PR TITLE
dpdk: Add header files for MUSL run-time

### PR DESCRIPTION
**Pull request by pprindeville**
Should be fixed upstream but for now, allow progress building with MUSL

### CODE REVIEW

**Comment by pprindeville** [comment]
cc: @zokl

**Comment by zokl** [comment]
> Should be fixed upstream but for now, allow progress building with MUSL

Thank you a will try it.

**Comment by zokl** [comment]
During the compilation, another place where it is needed include the unistd.h

```
cc-12.3.0_musl/lib/libc.so: warning: The fgetln() function cannot be safely ported, use getline(3) instead, as it is supported by GNU and POSIX.1-2008.
/home/votavon1/eshaper/staging_dir/toolchain-x86_64_gcc-12.3.0_musl/lib/gcc/x86_64-openwrt-linux-musl/12.3.0/../../../../x86_64-openwrt-linux-musl/bin/ld: drivers/libtmp_rte_bus_pci.a.p/bus_pci_linux_pci_vfio.c.o: in function `pci_vfio_set_bus_master':
pci_vfio.c:(.text+0x27): undefined reference to `pread64'
/home/votavon1/eshaper/staging_dir/toolchain-x86_64_gcc-12.3.0_musl/lib/gcc/x86_64-openwrt-linux-musl/12.3.0/../../../../x86_64-openwrt-linux-musl/bin/ld: pci_vfio.c:(.text+0x73): undefined reference to `pwrite64'
/home/votavon1/eshaper/staging_dir/toolchain-x86_64_gcc-12.3.0_musl/lib/gcc/x86_64-openwrt-linux-musl/12.3.0/../../../../x86_64-openwrt-linux-musl/bin/ld: drivers/libtmp_rte_bus_pci.a.p/bus_pci_linux_pci_vfio.c.o: in function `pci_vfio_map_resource_primary':
pci_vfio.c:(.text+0x74f): undefined reference to `pread64'
/home/votavon1/eshaper/staging_dir/toolchain-x86_64_gcc-12.3.0_musl/lib/gcc/x86_64-openwrt-linux-musl/12.3.0/../../../../x86_64-openwrt-linux-musl/bin/ld: pci_vfio.c:(.text+0x78c): undefined reference to `pread64'
/home/votavon1/eshaper/staging_dir/toolchain-x86_64_gcc-12.3.0_musl/lib/gcc/x86_64-openwrt-linux-musl/12.3.0/../../../../x86_64-openwrt-linux-musl/bin/ld: pci_vfio.c:(.text+0x7c3): undefined reference to `pread64'
/home/votavon1/eshaper/staging_dir/toolchain-x86_64_gcc-12.3.0_musl/lib/gcc/x86_64-openwrt-linux-musl/12.3.0/../../../../x86_64-openwrt-linux-musl/bin/ld: pci_vfio.c:(.text+0x810): undefined reference to `pread64'
/home/votavon1/eshaper/staging_dir/toolchain-x86_64_gcc-12.3.0_musl/lib/gcc/x86_64-openwrt-linux-musl/12.3.0/../../../../x86_64-openwrt-linux-musl/bin/ld: pci_vfio.c:(.text+0x841): undefined reference to `pread64'
/home/votavon1/eshaper/staging_dir/toolchain-x86_64_gcc-12.3.0_musl/lib/gcc/x86_64-openwrt-linux-musl/12.3.0/../../../../x86_64-openwrt-linux-musl/bin/ld: drivers/libtmp_rte_bus_pci.a.p/bus_pci_linux_pci_vfio.c.o:pci_vfio.c:(.text+0x9cc): more undefined references to `pread64' follow
/home/votavon1/eshaper/staging_dir/toolchain-x86_64_gcc-12.3.0_musl/lib/gcc/x86_64-openwrt-linux-musl/12.3.0/../../../../x86_64-openwrt-linux-musl/bin/ld: drivers/libtmp_rte_bus_pci.a.p/bus_pci_linux_pci_vfio.c.o: in function `pci_vfio_map_resource_primary':
pci_vfio.c:(.text+0xcde): undefined reference to `pwrite64'
/home/votavon1/eshaper/staging_dir/toolchain-x86_64_gcc-12.3.0_musl/lib/gcc/x86_64-openwrt-linux-musl/12.3.0/../../../../x86_64-openwrt-linux-musl/bin/ld: drivers/libtmp_rte_bus_pci.a.p/bus_pci_linux_pci_vfio.c.o: in function `pci_vfio_read_config':
pci_vfio.c:(.text+0x13d3): undefined reference to `pread64'
/home/votavon1/eshaper/staging_dir/toolchain-x86_64_gcc-12.3.0_musl/lib/gcc/x86_64-openwrt-linux-musl/12.3.0/../../../../x86_64-openwrt-linux-musl/bin/ld: drivers/libtmp_rte_bus_pci.a.p/bus_pci_linux_pci_vfio.c.o: in function `pci_vfio_write_config':
pci_vfio.c:(.text+0x1413): undefined reference to `pwrite64'
/home/votavon1/eshaper/staging_dir/toolchain-x86_64_gcc-12.3.0_musl/lib/gcc/x86_64-openwrt-linux-musl/12.3.0/../../../../x86_64-openwrt-linux-musl/bin/ld: drivers/libtmp_rte_bus_pci.a.p/bus_pci_linux_pci_vfio.c.o: in function `pci_vfio_ioport_read':
pci_vfio.c:(.text+0x14c5): undefined reference to `pread64'
/home/votavon1/eshaper/staging_dir/toolchain-x86_64_gcc-12.3.0_musl/lib/gcc/x86_64-openwrt-linux-musl/12.3.0/../../../../x86_64-openwrt-linux-musl/bin/ld: drivers/libtmp_rte_bus_pci.a.p/bus_pci_linux_pci_vfio.c.o: in function `pci_vfio_ioport_write':
pci_vfio.c:(.text+0x1539): undefined reference to `pwrite64'
collect2: error: ld returned 1 exit status

```

**Comment by pprindeville** [comment]
What’s the other place? They all seem to be in the same source file.

**Comment by zokl** [comment]
> What’s the other place? They all seem to be in the same source file.

I apologize for my inaccuracy, yes it is the same pc_vfioi.c file but different functions.

**Comment by zokl** [comment]
> > What’s the other place? They all seem to be in the same source file.
> 
> I apologize for my inaccuracy, yes it is the same pc_vfioi.c file but different functions.

The problem is in `_LARGEFILE64_SOURCE` switch. It is disabled by default. If I enable it, the compilation successfully finishes. 

`TARGET_CFLAGS+=-D_LARGEFILE64_SOURCE` in DPDK Makefile solve this problem.

**Comment by zokl** [comment]
Finaly, compilation flag `TARGET_CFLAGS+=-D_GNU_SOURCE` is the right way how to compile with MUSL.

**Comment by pprindeville** [comment]
Do you have an example of the errors logs related to `_LARGEFILE64_SOURCE`?

**Comment by pprindeville** [comment]
> Finaly, compilation flag `TARGET_CFLAGS+=-D_GNU_SOURCE` is the right way how to compile with MUSL.

Using `-D_LARGEFILE64_SOURCE` didn't work?  That's more POSIX standard and doesn't depend on GNU-isms in the headers...

**Comment by zokl** [comment]
> Do you have an example of the errors logs related to `_LARGEFILE64_SOURCE`?



> > Finaly, compilation flag `TARGET_CFLAGS+=-D_GNU_SOURCE` is the right way how to compile with MUSL.
> 
> Using `-D_LARGEFILE64_SOURCE` didn't work? That's more POSIX standard and doesn't depend on GNU-isms in the headers...

Yes. It works with this flag. May I change it instead of GNU…?

**Comment by pprindeville** [comment]
> > Using `-D_LARGEFILE64_SOURCE` didn't work? That's more POSIX standard and doesn't depend on GNU-isms in the headers...
> 
> Yes. It works with this flag. May I change it instead of GNU…?

I'd rather we stick with something portable.

**Comment by zokl** [comment]
> > > Using `-D_LARGEFILE64_SOURCE` didn't work? That's more POSIX standard and doesn't depend on GNU-isms in the headers...
> > 
> > 
> > Yes. It works with this flag. May I change it instead of GNU…?
> 
> I'd rather we stick with something portable.

OK, I'll take advice from more experienced :-)

```
ifneq ($(CONFIG_USE_MUSL),)
TARGET_CFLAGS += -D_LARGEFILE64_SOURCE
endif

```

**Comment by pprindeville** [comment]
> OK, I'll take advice from more experienced :-)
> 
> ```
> ifneq ($(CONFIG_USE_MUSL),)
> TARGET_CFLAGS += -D_LARGEFILE64_SOURCE
> endif
> ```

I think it’s safe to set it unconditionally.

**Comment by pprindeville** [comment]
Or use CONFIG_64BIT

**Comment by zokl** [comment]
> > OK, I'll take advice from more experienced :-)
> > ```
> > ifneq ($(CONFIG_USE_MUSL),)
> > TARGET_CFLAGS += -D_LARGEFILE64_SOURCE
> > endif
> > ```
> 
> I think it’s safe to set it unconditionally.

Other packages in the repository use this condition to enable this feature. I am not sure what it does with glibc. The compilation has finished, but I need to test it... https://github.com/search?q=repo%3Aopenwrt%2Fpackages%20D_LARGEFILE64_SOURCE&type=code

**Pull request closed without merging**
